### ISSUE TITLE
Request - utilize gamedata file

### ISSUE THREAD

**Issue by sneak-it** [accelerator74/Cleaner#10]
A bit of a feature request here, it would be helpful to utilize a gamedata file rather than sigs being compiled into the extension. This would be great if a breaking game update were to happen, then recompiling the extension would not be a requirement.

**Comment by accelerator74** [comment]
Previous versions were using gamedata, but this is confusing. For example, for tf2 and css, the internal functions of the engine are used, which does not require the use of signatures.

These signatures very rarely change. There have already been many updates, and the signatures are still alive for more than 4 years :)
