### ISSUE TITLE
Cleaner not cleaning

### ISSUE THREAD

**Issue by walliski** [accelerator74/Cleaner#12]
There are discussions on the AlliedModders Discord that the fixed version of the Cleaner does not work. That it would load and not crash the server, but that it does not remove any messages.

Nikooo777 on the Discord mentioned that this works (on some older version of cleaner that reads gamedata files):
```
        "Offsets"
        {
            "ServerConsolePrint"
            {
                "linux"            "576"
            }
        }
```

**Comment by nikooo777** [comment]
yeah, 
```
1sm exts info
 File: cleaner.ext.2.csgo.so
 Loaded: Yes (version 1.8.0-manual)
 Name: Equinox Console Cleaner (Bite me alien boi)
 Author: Zephyrus, Accelerator (http://www.sourcemod.net/)
 Binary info: API version 8 (compiled Apr 29 2017 15:43:43)
 Method: Loaded by SourceMod
```

with that offset it works fine. took me a while to figure it out, they bumped the function down 1.

**Comment by accelerator74** [comment]
Thanks! It's hard to test the work without own server :)
