### ISSUE TITLE
GLIBCXX_3.4.21 not found

### ISSUE THREAD

**Issue by noillt** [accelerator74/Cleaner#18]
Error:
> <FAILED> file "cleaner.ext.2.css.so": bin/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/server/serverfiles/cstrike/addons/sourcemod/extensions/cleaner.ext.2.css.so)

Fix:
```sh
mv /home/server/serverfiles/bin/libstdc++.so.6 /home/server/serverfiles/bin/libstdc++.so.6.bak
sudo ln -sf /usr/lib32/libstdc++.so.6 /home/server/serverfiles/bin/libstdc++.so.6
sudo chown server:server /home/server/serverfiles/bin/libstdc++.so.6
```

**Comment by accelerator74** [comment]
It is better to use the libstdc++ library built into the OS. You can safely delete `libstdc++.so.6` from the bin folder.
