### ISSUE TITLE
BUG Servers CSGO - Cleaner.cfg

### ISSUE THREAD

**Issue by paulocrash** [Accelerator74/Cleaner#2]
`L 01/13/2018 - 03:57:12: [SM] Unable to load extension "cleaner.ext": Could not read configs/cleaner.cfg.`

As you can see, you can not read config **cleaner.cfg**.

Check the folder in question and this file is not listed.

**Comment by Accelerator74** [comment]
Create cleaner.cfg with your phrases in addons/sourcemod/configs
